### ISSUE TITLE
Stream error not handled correctly

### ISSUE THREAD

**Issue by Prinzhorn** [trentm/node-bunyan#108]
It's late, so maybe I'm on the wrong track (I come from https://github.com/newrelic/node-newrelic/issues/76).

Anyway, the documentation says

> Bunyan re-emits error events from the created WriteStream.

https://github.com/trentm/node-bunyan#stream-errors

Given this `index.js`

``` js
var bunyan = require('bunyan');
var log = bunyan.createLogger({name: "myapp"});

setInterval(function() {
    log.info("hi");
}, 500);

log.on('error', function(err, stream) {
    process.exit(1);
});
```

and then piping the output to a named pipe created by `mkfifo mypipe` using

```
node index.js > mypipe
```

I get the following error when I close the pipe

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

Shouldn't the program just exit without an error? I do handle the error event.

**Comment by basickarl** [comment]
I'm also getting this error:

```
karl@karl-laptop:~/www/instantynode/src$ node app.js | bunyan -o short
bunyan: command not found
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

I do not get the error however if with the following:

```
karl@karl-laptop:~/www/instantynode/src$ node app.js
```

**Comment by yveslange** [comment]
@basickarl did you install `bunyan` globally ?

`npm install -g bunyan`

Look at the second line of the error: `bunyan: command not found`

**Comment by deadbeef84** [comment]
I'm also getting `Error: This socket is closed` when piping, I took a quick look at the [bunyan cli source code](https://github.com/trentm/node-bunyan/blob/master/bin/bunyan#L1607) and it appears to look for this error, however in node 6.0.0 this error message was changed and [the ending period was removed](https://github.com/nodejs/node/blob/5de3cf099cd01c84d1809dab90c041b76aa58d8e/lib/net.js#L683), so now the test in bunyan fails. Anyone willing to fix this or do you want me to send a PR?

**Comment by trentm** [comment]
@deadbeef84 The "This socket is closed" thing is in the `bunyan` CLI. The OP is about the bunyan module. So I believe these are separate issues. It would be helpful to have a separate ticket (with repro details) for what you are seeing. I'm also curious if recent changes in #246 affect what you see. Also I have some not-quite-yet-commited work around `bunyan` CLI exit handling that might be relevant as well.

**Comment by trentm** [comment]
It has been *years*, so I assume @Prinzhorn that you have moved on. :)  However, for completeness, and because I've been handling other EPIPE and exit-handling related Qs for bunyan of late (as I've improved in my understanding), I'll answer the OP here.

Others on this thread, if you still have issues with the latest Bunyan, please open new tickets and I'll try to answer them there. Note that the issues are different with "bunyan the library" usage vs "`bunyan` the CLI" usage.

* * *

At the time of the OP, the current version of bunyan was 0.22.0. Since then, the behaviour of EPIPE handling with bunyan *the library* has not changed. However, since then the `reemitErrorEvents` option has been added to Bunyan streams and <https://github.com/trentm/node-bunyan#stream-errors> has been updated. This was added in version 1.7.0 as part of pull #318 ([changelog entry](https://github.com/trentm/node-bunyan/blob/master/CHANGES.md#170)).

Bunyan re-emitting of stream errors was initially added *only for Bunyan streams of type=file*. Writing to `process.stdout` (Bunyan's default) is a Bunyan stream of type="stream". To re-emit errors on that stream requires the explicit `reemitErrorEvents: true`. If we change the original code sample to:

```javascript
var bunyan = require('bunyan');
var log = bunyan.createLogger({
    name: "myapp",
    streams: [
        {
            stream: process.stdout,
            reemitErrorEvents: true
        }
    ]
});

setInterval(function() {
    log.info("hi");
}, 500);

log.on('error', function(err, stream) {
    process.exit(1);
});
```

Then it works as intended. In one terminal:

```
$ cat read-from-mypipe.sh
#!/bin/bash
PIPE=$1
trap "rm -f $PIPE" EXIT

if [[ ! -p $PIPE ]]; then
    mkfifo $PIPE
fi

while true
do
    if read line <$PIPE; then
        echo $line
    fi
done

$ bash read-from-mypipe.sh mypipe
{"name":"myapp","hostname":"danger0.local","pid":25580,"level":30,"msg":"hi","time":"2017-05-16T06:37:08.407Z","v":0}
{"name":"myapp","hostname":"danger0.local","pid":25580,"level":30,"msg":"hi","time":"2017-05-16T06:37:08.918Z","v":0}
{"name":"myapp","hostname":"danger0.local","pid":25580,"level":30,"msg":"hi","time":"2017-05-16T06:37:09.424Z","v":0}
{"name":"myapp","hostname":"danger0.local","pid":25580,"level":30,"msg":"hi","time":"2017-05-16T06:37:09.930Z","v":0}
^C
```

and in a second terminal:

```
$ node issue108.js >mypipe

$ echo $?
1
```
