### ISSUE TITLE
What's the best way to parse bunyan logs without CLI?

### ISSUE THREAD

**Issue by brycepj** [trentm/node-bunyan#271]
New to bunyan -- if I wanted to render some of the data from the logs on a web page, I need to read the log file, parse it, and go from there. But bunyan files aren't pure json, they're objects stacked on top of one another. Is there a means within bunyan to convert bunyan logs to pure json, so they don't break json parsers?

**Comment by mpareja** [comment]
Use split stream to break the stream up into newline delimited chunks and then JSON parse them if you'd like. Quick snippet sample:

```
  var split = require('split');
  var entries = split('\n', function (input) {
      if (!input) { return undefined; } // don't emit on trailing or keep alive new lines
      return JSON.parse(input);
    });
  rawdataStream.pipe(entries).on('data', function (entry) { ..... });
```

**Comment by brycepj** [comment]
Okay, so I'll need to do it by hand. Good to know, and thanks for the snippet @mpareja.

**Comment by gpsinghsandhu** [comment]
I ended up here because people at our company wanted to see nicer logs with bunyan CLI and suppress some fields. So taking inspiration from @mpareja (starting with his snippet :) ), I created this small package - [tunyan](https://www.npmjs.com/package/tunyan).

This is a first draft and I will keep updating it, hope it helps someone.
