### ISSUE TITLE
Possible to pipe CLI on Windows?

### ISSUE THREAD

**Issue by RanzQ** [trentm/node-bunyan#322]
I'm using node v4.2.2 on Windows and I tried to use `node server.js | bunyan` but I don't see any output from my script. Works on linux. And running `bunyan` works too, it transforms a json log string if I paste it.

**Comment by RanzQ** [comment]
The issue seems to be caused by PowerShell, which apparently doesn't support pipes. Works on CMD.exe.

**Comment by GustavSt** [comment]
I have the same issue. Running `gulp server | bunyan` doesn't work with powershell, but it does work with cmd.exe.

And unfortunately it haven't started working for me..
Any idea what the issue can be?

**Comment by RanzQ** [comment]
@GustavSt actually I just tested and doesn't seem to work for me either. Why I thought it worked is that I use [better-npm-run](https://github.com/benoror/better-npm-run) and then in package.json I have:

```
  "scripts": {
    "start": "node ./node_modules/better-npm-run start | bunyan",
  },
  "betterScripts": {
    "start": {
      "command": "node server.js"
    }
  },
```
That way it works for unknown reason. :)

This doesn't print anything but the server starts `node server.js | bunyan`.

**Comment by blakew** [comment]
Had the same issue. From within Powershell, piping to `bunyan` produces no output. But if you pipe from a package.json script (can be `start` or whatever else), it suddenly works fine.

**Comment by kolbma** [comment]
That's no surprise that the pipe to bunyan program doesn't work in powershell.  
The pipe symbol is used by the powershell itself and works with objects. And bunyan doesn't know anything about powershell objects.

https://docs.microsoft.com/en-us/powershell/scripting/getting-started/fundamental/understanding-the-windows-powershell-pipeline

You can do something like `cmd /C "node app.js | bunyan"` in a powershell.  
That's why also the npm scripts work, because they start a cmd to execute the commands.

**Comment by potatopotat0** [comment]
In my case none of the above would work for me. Tried running from cmd, pwsh, bash, but only get the unformatted output.
Running `bunyan` and pasting the output do output the result formatted, however.
