### ISSUE TITLE
process.stdout returning isWritable false

### ISSUE THREAD

**Issue by weagle08** [trentm/node-bunyan#382]
I'm having an issue on linux where I use process.stdout as a write stream for the logger, but in bunyan.js line 307 the isWritable function is returning false when the obj.writable property is true.

**Comment by weagle08** [comment]
the type of process.stdout on linux appears to be a socket

**Comment by michaelnisi** [comment]
How do you create the logger? Please post the code.

**Comment by weagle08** [comment]
https://github.com/sameke/bunyan-log/blob/master/lib/Logger.js

**Comment by michaelnisi** [comment]
Looks OK to me, and `isWritable` would return `true` because `typeof (obj.write) === 'function'`. You didn't mention the error you've been getting yet.

**Comment by weagle08** [comment]
I don't get any error, just a crash.

**Comment by weagle08** [comment]
Also after looking into this a little more it works as expected if you run as admin (on windows) or sudo (on linux). However if you are not one of those bunyan just seems to crash the node process with no type of error message output because of how you guys are checking the stream with an assert.  May try to submit a fix for this soon if you don't mind me removing the asserts which IMO are bad practice to use for production code (correct me if I'm wrong).

**Comment by michaelnisi** [comment]
Regardless of the environment, production or not, asserts are used to communicate that the program encountered an unhandled condition causing it to enter undefined state. As a user you can either catch the thrown exception or crash, which is the smarter choice—especially in production—where you don't want any part of your program in undefined state, but [fail fast](https://en.wikipedia.org/wiki/Fail-fast).

Take this issue as an example, you raised it because the exception clearly signalled something is wrong. [Error Handling in Node.js](https://www.joyent.com/developers/node/design/errors) is interesting.

Sorry for not being of much help regarding your actual issue, but let me say this, it seems utterly strange that `process.stdout` should be of any other type than `stream.Writable`—whichever user.
