### ISSUE TITLE
Reason for the "v" element in log output

### ISSUE THREAD

**Issue by Cyberuben** [trentm/node-bunyan#383]
I can't seem to find out anywhere what the use and reason for the `"v"` element is in the json output. I've looked through the source quickly, as well as through the documentation but without luck. All examples of log output always have the `"v"` value set to `0`, which makes me wonder why it's there in the first place.

**Comment by voxpelli** [comment]
It's the version of the log, the [LOG_VERSION](https://github.com/trentm/node-bunyan/blob/ffc6355b6fc7af7faaffcfc35c86c6f76f5cec96/lib/bunyan.js#L1006).

The justification can be found [higher up in that file](https://github.com/trentm/node-bunyan/blob/ffc6355b6fc7af7faaffcfc35c86c6f76f5cec96/lib/bunyan.js#L13):

> This will be incremented if there is any backward incompatible change to the log record format. Details will be in 'CHANGES.md' (the change log).

So seems to be there so that a parser of the output can know what to expect of the data.

**Comment by Cyberuben** [comment]
My bad, I was explicitly searching for `"v"` and forgot to check `'v'` as this wasn't what was shown in the output

**Comment by stephanebruckert** [comment]
Can we hide or override this log version "v"? Some of our non-JS services are already using "v" as part of the JSON logs and for a different purpose. Really not sure why the LOG_VERSION of Bunyan needs to be part of everyone's logs. Please help!

**Comment by trentm** [comment]
@stephanebruckert can you opena separate issue to ask please? Given this one is closed, I fear your Q will just get lost.

**Comment by stephanebruckert** [comment]
https://github.com/trentm/node-bunyan/issues/462
