### ISSUE TITLE
`.fatal` kills the app

### ISSUE THREAD

**Issue by peter-mouland** [trentm/node-bunyan#432]
is `.fatal` meant to kill the app or is it meant to just log a message marked as `fatal`?

In my current app, we had (incorrectly) used `logger.fatal` for all response status's that weren't 200. This means that the app was killed even on 404 pages.  Is this meant to be the case or is this likely to be a config error?

thanks for your help

```js
// errorHandler.js
   ...
    const logger = getLogger();
    logger.fatal({
      status: res.statusCode,
      err
    });
```
```js
// logger.js

const createHoneybadgerStream = require('/lib/createHoneybadgerStream')
const bunyan = require('bunyan')

module.exports = function getLogger() {

    function createDefaultLogStreamsConfig() {
      const streams = [
        { path: config.logFile },
        { type: 'stream', stream: createHoneybadgerStream(), level: 'error' }
      ];
      streams.push({ type: 'stream', stream: process.stdout,  level: 'info' });
      return streams;
    }

      logger = bunyan.createLogger({
        name: config.appName,
        streams: createDefaultLogStreamsConfig(),
        serializers: bunyan.stdSerializers
      });

    return logger;
};
```

**Comment by peter-mouland** [comment]
Does anyone know if using the `.fatal` function was killing the app because that is how the function is designed, or because it is a mistake?

(removing the use of `.fatal` and the app wouldn't have been killed)

thanks

**Comment by voxpelli** [comment]
The `fatal()` method is created just like all the other methods: https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L1077

It should not kill your app. If it is, then it's probably because something causes the logging to throw an exception and then you need to look at what exception says and see if that helps you.

(Side note: Using the `fatal` level on a `404` also sounds a bit wrong: https://github.com/trentm/node-bunyan#levels A `warn` or `error` level would probably be more appropriate – which one depending on whether you have eg. a backend API or a user facing application)

**Comment by peter-mouland** [comment]
thanks for pointing out the creation code- must have been something funny in our app.

**Comment by trentm** [comment]
thanks for following up!
