### ISSUE TITLE
Log deep objects containing [Object object]

### ISSUE THREAD

**Issue by albertvazquezm** [trentm/node-bunyan#439]
Hi,

When generating the log message, you're using util.format, which uses util.inspect to stringify all javascript objects. The problem is that util.inspect has a depth param that defaults to 2.

That cause our deep objects to contain [Object object] parts.

Is there a way to configure depth param?

Thanks!

**Comment by trentm** [comment]
@albertvazquezm  Can you show an example of your log line? 

```
log.info('my obj is: %s', obj);   // uses util.format
log.info({obj: obj}, 'my obj is');  // does not use util.format; uses JSON.stringify
```

The second form is generally preferred, IMO. It avoids the `[Object object]` thing for deeper objects. It also results in an object in the log record, rather than a string, which means it is more filterable.

About setting that depth level to something else: I notice that more recent node versions allow you to set it for the whole process: https://nodejs.org/docs/latest/api/all.html#util_custom_inspection_functions_on_objects

**Comment by albertvazquezm** [comment]
Hi @trentm thanks for your response. 

Neither `this._logger.debug('Configuration retrieved.  Value = ', message);` or `this._logger.debug(message, 'Configuration retrieved.  Value = ');` it's working for me, still getting `streams: [ [Object], [Object], [Object] ] }`.

I have 1.8.0 version

Thanks!
