### ISSUE TITLE
should serializers be mutating in place?

### ISSUE THREAD

**Issue by brandonmp** [trentm/node-bunyan#464]
i have a serializer:

```
export const serializeScrapeResults = (scrapeResults) => {
    let serialResults = scrapeResults

    let imageCount = Array.isArray(serialResults.photos) === true ?
        serialResults.photos.length : 0
    delete serialResults.photos
    serialResults.imageCount = imageCount
    return serialResults
}
```

when I pass `scrapeResults` object to `log.info`, the `serializer` is mutating the original object (a fact I realized, regrettably, well after it'd done some damage to my data)

I'm def. a little hazy on mutability and references in `javascript`, but this feels like somewhat counter-intuitive behavior. 

I've fixed it w/ a simple:

`let serialResults = Object.assign({}, scrapeResults)`

but is there a way to interact with `serializers` in a way that's `immutable` by default? [Pit of Success](https://blog.codinghorror.com/falling-into-the-pit-of-success/), and all that.

**Comment by trentm** [comment]
@brandonmp Sorry for the crazy delay in responding.

Serializers should definitely not be mutating in-place. It is the responsibility of the serializer function to be safe here. I don't want to have Bunyan attempt to protect from this foot-gun because:

- I suspect the perf impact would be large. Creating a shallow or deep copy of any object passed to a serializer would be heavy.
- The serializer will already be running arbitrary code on the object. There is no general way to make that totally safe from any serializer code.

Granted, however, that this requirement on customer serializers isn't obvious. I'll try to update the docs on that.

**Comment by trentm** [comment]
commit b33b7e5 coming with some better docs for this.

**Comment by trentm** [comment]
Added doc section to try to help: https://github.com/trentm/node-bunyan/tree/master#requirements-for-serializers-functions

**Comment by brandonmp** [comment]
great, thanks @trentm , points well-taken & new docs are perfectly clear
