### ISSUE TITLE
Child loggers don't pick up new parent streams

### ISSUE THREAD

**Issue by juanpaco** [trentm/node-bunyan#468]
And it is quite possible that is the intended behavior.  I'm in a situation where I calling `child` on a logger before I'm able to add all of its streams.  At a point in the future (promise resolution on an async stream), I add the stream to the logger.  However, the children don't pick up the new stream.

I see in the code why that is happening, though I don't know if you would like the child loggers to pick up streams later added to the parent or not.  Is it the intent that child streams would not pick up streams added to their parents after the call to `child` is made?

**Comment by trentm** [comment]
@juanpaco Sorry for the delay in responding.

I think (from reading the code) that a child *will* inherit changes to its parent's streams if the second `simple` arg to `log.child` is true:

```javascript
var clog = log.child({component: "foo"}, true);
```

So there is a subtle difference in child logger behaviour depending on that `simple` arg. This isn't really intentional. `simple` was added later, so the original behaviour has been that a child logger doesn't inherit changes to its parent's streams.

Bunyan could be made to do that by having child loggers have both `.streams` and `.parentStreams` (or whatever name). Thinking out loud now: However, I wonder if that would be worth the potential perf impact (would a more deeply nest child logger, the result of `log.child().child()...`, need to walk a chain of `.parentStreams` to find all the streams it should write to) and added code complexity?

I don't have particular use cases in mind to justify the added code (and possibly perf) to support that behaviour. If the `simple=true` case answers your use case, that would be interesting to know. FWIW, I have plans (https://github.com/trentm/node-bunyan/blob/master/TODO.md#changes-to-ctor-and-logchild-to-separate-fields-from-config) to make the distinction between config and fields more explicit in a future bunyan version.
