### ISSUE TITLE
Is this project no longer in active development?

### ISSUE THREAD

**Issue by LeonFedotov** [trentm/node-bunyan#640]

**Comment by leomeloxp** [comment]
@LeonFedotov this issue seems to be a rewording of #586 

If you look at how that discussion ended it seems fair to say that the project is no longer active. 😢

**Comment by markstos** [comment]
New releases in the 1.8.x and 2.0.x series were released a couple of days ago by @trentm.

**Comment by markstos** [comment]
On way to answer this question is to check the Network Graph:  https://github.com/trentm/node-bunyan/network

If an open source project has vitality, forks will continue to thrive even if the primary maintainer isn't.

Primary maintainers are usually unpaid volunteers and owe you nothing-- they have given you the software for free in the first place. If the project has value to you, get involved. Reviewing and responding to open issues is a good start.

Having everyone using Bunyan move to `pino` doesn't really solve the problem of community engagement, it just shifts the maintenance burden from one over-burdened volunteer to another, who will be more likely to burn out and the requests for more work increase disproportionately to the volunteers willing to help maintain the project.

**Comment by LeonFedotov** [comment]
Answer: this project had came back to life!

**Comment by mastermatt** [comment]
@markstos it sounded like you needed to get that off your chest, but I think you missed the good-natured intention of the OP's question. Having a thriving fork community is great, but the reality is that when a dev is shopping for a lib, either for a new project or maintaining a legacy one, they have to pick one. And this lib was unmaintained for years.

I disagree that a high number of forks represents a healthy project. On the contrary, unless one or a few forks emerge as being popular, a high number of forks means the community is not benefiting from contributions. 

When I look to give back to a lib that I use, my hope is that it could benefit others. So forking for my own gain is not desired and it makes sense to use and contribute to an active project. Moving to something like `pino` did help with community engagement because contributions are being merged upstream and distributed back to the community. 

I absolutely agree that maintainers owe us nothing. Burn out is real. If maintainers decide to step away for awhile or forever from a project, that is their prerogative, but the expectation **should be**  that users should jump ship if there is an alternative. 

All that being said, I personally don't feel this original question has been answered. Yes, two patch versions were published and there have been a handful of commits in the last week. But that in itself does not mean this project is back in full swing after three years. It would be appreciated if the state of the project could be spoken to. Is @trentm planning on being a solo, active maintainer for the foreseeable future? Have other devs joined the project to help out? Is there a desire to have more folks help out in a core manner (triage, CR, etc)? Looking at the backlog on this repo, there doesn't seem to be a shortage of people _wanting_ to help, but the _how to help_ is fuzzy.

**Comment by markstos** [comment]
@mastermatt I did not comment on high number of forks. Having some activity somewhere in the ecosystem is a sign of vitality. 

>  a high number of forks means the community is not benefiting from contributions.

But I'll comment on a high number of forks now now: A high number of forks with none of them actually released to NPM is a sign that a lot of people are using the project but none of them have stepped up fill the void that the inactive maintainer left. They are forking primarily for private benefit. 

Here, the lack of an answer from the maintainer is an answer. Folks should step up to help with maintenance of this project or fork-and-**Release** and move on.

**Comment by mastermatt** [comment]
... or use Pino.
