### ISSUE TITLE
`v` always 0 despite bunyan version 1.x released and version 2.x in the making

### ISSUE THREAD

**Issue by f0o** [trentm/node-bunyan#694]
According to the docs:
```
v: Required. Integer. Added by Bunyan. Cannot be overridden. This is the Bunyan log format version (require('bunyan').LOG_VERSION). The log version is a single integer. 0 is until I release a version "1.0.0" of node-bunyan. Thereafter, starting with 1, this will be incremented if there is any backward incompatible change to the log record format. Details will be in "CHANGES.md" (the change log).
```

So should this text be adjusted or is `v` getting updated?

**Comment by trentm** [comment]
That 'v' is meant to be for the bunyan JSON format version, which is independent of the version of bunyan-the-library. For example the bunyan library version would get a major version bump if it dropped compatibility somehow, but it might still support the exact same bunyan log/JSON format.

> 0 is until I release a version "1.0.0" of node-bunyan.

Yah, so that never happened. That's my bad I guess. At this point I hope it doesn't matter much to any users that it is still at v=0.  Perhaps we should just remove that one sentence.
